name: DVC Tracking with Github Actions
on: [push]
jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Running_updates
        env:
          GH_TOKEN: ${{ github.token }}
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          pip install -r requirements.txt 
          dvc repro
          git fetch --prune

          # Access the commit SHA using github.sha
          COMMIT_SHA=${{ github.sha }}
          echo "Commit SHA: $COMMIT_SHA" > report.md  # Write the commit SHA to the report.md file

          # Append metrics.json content to report.md
          cat metrics.json >> report.md
